import 'package:flutter/material.dart';
import 'package:get_storage/get_storage.dart';

class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  final _storage = GetStorage();
  final ValueNotifier<Locale> localeNotifier = ValueNotifier(
    const Locale('id', 'ID'),
  );

  void init() {
    final String? langCode = _storage.read('language_code');
    if (langCode != null) {
      localeNotifier.value = Locale(langCode);
    }
  }

  void changeLocale(String langCode) {
    localeNotifier.value = Locale(langCode);
    _storage.write('language_code', langCode);
  }

  String translate(String key) {
    final String lang = localeNotifier.value.languageCode;
    return _localizedValues[lang]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'id': {
      'tentang_saya': 'Tentang Saya',
      'penghuni': 'Penghuni',
      'kendaraanku': 'Kendaraanku',
      'unverified': 'Menunggu',
      'verified': 'Diterima',
      'kontak': 'Kontak',
      'akun': 'Akun',
      'data_pribadi': 'Data Pribadi',
      'pengaturan': 'Pengaturan',
      'visi_misi': 'Visi Misi',
      'ketentuan_privasi': 'Ketentuan & Privasi',
      'keluar': 'Keluar',
      'pilih_bahasa': 'Pilih Bahasa',
      'bahasa': 'Bahasa',
      'batal': 'Batal',
      'halo': 'Halo',
      'selamat_datang': 'Selamat Datang di Entrify',
      'menu_utama': 'Menu Utama',
      'daftar_kendaraan': 'Daftar\nKendaraan',
      'riwayat_kendaraan': 'Riwayat\nKendaraan',
      'pengumuman': 'Pengumuman',
      'see_more': 'Lihat Semua',
      'info_pengumuman': 'Informasi Pengumuman Bulan Ini',
      'tidak_ada_pengumuman': 'Tidak ada pengumuman',
      'data_keluar_masuk': 'Data Kendaraan Keluar-Masuk.',
      'search_placeholder': 'Cari plat/tipe',
      'tidak_ada_data': 'Tidak ada data ditemukan',
      'tanggal': 'Tanggal',
      'status': 'Status',
      'jenis': 'Jenis',
      'masuk': 'Masuk',
      'keluar_status': 'Keluar',
      'motor': 'Motor',
      'mobil': 'Mobil',
      'semua': 'Semua',
      'hapus_filter': 'Hapus Filter',
      'pilih': 'Pilih',
      'lihat_detail': 'Lihat Detail',
      'tambah_kendaraan': 'Tambah Kendaraan',
      'pending': 'Menunggu',
      'rejected': 'Ditolak',
      'periode': 'Periode',
      'daftar_pengumuman': 'Daftar Pengumuman',
      'informasi_pengumuman': 'Informasi Pengumuman',
      'visi_misi_content':
          'Visi:\nMenjadi platform manajemen hunian terdepan yang memudahkan interaksi antara pengelola dan penghuni.\n\nMisi:\n1. Memberikan layanan yang transparan dan efisien.\n2. Meningkatkan keamanan dan kenyamanan lingkungan.\n3. Membangun komunitas yang harmonis.',
      'ketentuan_privasi_content':
          '1. Data Pengguna:\nKami menjaga kerahasiaan data pribadi Anda dan tidak akan membagikannya kepada pihak ketiga tanpa izin.\n\n2. Penggunaan Aplikasi:\nAplikasi ini digunakan untuk keperluan manajemen hunian dan komunikasi antar warga.\n\n3. Keamanan:\nKami berkomitmen untuk menjaga keamanan data dan transaksi dalam aplikasi ini.',
      'tutup': 'Tutup',
      'detail_kendaraan': 'Detail Kendaraan',
      'nama_pemilik': 'Nama Pemilik',
      'plat_kendaraan': 'Plat Kendaraan',
      'jenis_kendaraan': 'Jenis Kendaraan',
      'tanggal_waktu': 'Tanggal & Waktu',
      'detail_pengumuman_title': 'Detail Pengumuman',
      'uploaded': 'Diunggah',
      'deskripsi': 'Deskripsi',
      'tanggal_kegiatan': 'Tanggal Kegiatan',
      'uploaded_by': 'Oleh',
      'pengurus_keamanan': 'Pengurus Keamanan',
      'memuat': 'Memuat...',
      'tambah_pengumuman': 'Tambah Pengumuman',
      'hapus_pengumuman': 'Hapus Pengumuman',
      'konfirmasi_hapus_pengumuman':
          'Apakah Anda yakin ingin menghapus pengumuman ini?',
      'hapus': 'Hapus',
      'pengumuman_dihapus': 'Pengumuman berhasil dihapus',
      'admin': 'Admin',
      'judul_kegiatan': 'Judul Kegiatan',
      'hint_judul': 'Contoh: Gotong Royong',
      'hint_deskripsi': 'Deskripsikan kegiatan...',
      'pilih_tanggal': 'Pilih Tanggal',
      'jam_kegiatan': 'Jam Kegiatan',
      'pilih_jam': 'Pilih Jam',
      'submit': 'Kirim',
      'pilih_tanggal_valid': 'Mohon pilih tanggal',
      'pilih_jam_valid': 'Mohon pilih jam',
      'pengumuman_ditambahkan': 'Pengumuman berhasil ditambahkan',
      'approved': 'Disetujui',
      'unknown': 'Tidak Diketahui',
      'na': 'N/A',
      'approved_at': 'Disetujui pada',
      'submitted_at': 'Diajukan pada',
      'rejected_at': 'Ditolak pada',
      'kategori': 'Kategori',
      'keterangan': 'Keterangan',
      'foto': 'Foto',
      'tanggal_terdaftar': 'Tanggal Terdaftar',
      'approve': 'Setujui',
      'reject': 'Tolak',
      'confirm_approve': 'Apakah Anda yakin ingin menyetujui kendaraan ini?',
      'confirm_reject': 'Apakah Anda yakin ingin menolak kendaraan ini?',
      'vehicle_approved': 'Kendaraan berhasil disetujui',
      'vehicle_rejected': 'Kendaraan berhasil ditolak',
      'daftar_penghuni': 'Daftar Penghuni',
      'no_residents_found': 'Tidak ada penghuni ditemukan',
      'tambah_penghuni': 'Tambah Penghuni',
      'nama_penghuni': 'Nama Penghuni',
      'alamat_penghuni': 'Alamat Penghuni',
      'id_penghuni': 'ID Penghuni',
      'nomor_handphone': 'Nomor Handphone',
      'penghuni_berhasil_ditambahkan': 'Penghuni berhasil ditambahkan',
      'id_sudah_digunakan': 'ID Penghuni sudah digunakan',
      'username_sudah_digunakan': 'Username sudah digunakan',
      'field_tidak_boleh_kosong': 'Field ini tidak boleh kosong',
      'tidak_ada_kendaraan_terdaftar': 'Tidak ada kendaraan terdaftar.',
      'error_loading_vehicles': 'Gagal memuat kendaraan',
      'username': 'Username',
      'password': 'Password',
      'alamat': 'Alamat',
      'kelola_penghuni': 'Kelola\nPenghuni',
      'kelola_kendaraan': 'Kelola\nKendaraan',
      'error_loading_announcements': 'Gagal memuat pengumuman',
      'kalender': 'Kalender',
      'no_title': 'Tanpa Judul',
      'informasi_terbaru': 'Informasi Terbaru',
      'kegiatan_pada': 'Kegiatan pada',
      'no_description': 'Tidak ada deskripsi',
      'terdaftar': 'Terdaftar',
      'kedatangan': 'Kedatangan',
      'foto_kendaraan': 'Foto Kendaraan',
      'Su': 'Min',
      'Mo': 'Sen',
      'Tu': 'Sel',
      'We': 'Rab',
      'Th': 'Kam',
      'Fr': 'Jum',
      'Sa': 'Sab',
      'month_1': 'Jan',
      'month_2': 'Feb',
      'month_3': 'Mar',
      'month_4': 'Apr',
      'month_5': 'Mei',
      'month_6': 'Jun',
      'month_7': 'Jul',
      'month_8': 'Agt',
      'month_9': 'Sep',
      'month_10': 'Okt',
      'month_11': 'Nov',
      'month_12': 'Des',
      'profil_admin': 'Profil Admin',
      'kantor_pengelola': 'Kantor Pengelola',
      'kendaraan_disetujui': 'Kendaraan Disetujui',
      'kendaraan_ditolak': 'Kendaraan Ditolak',
      'kendaraan_dengan_plat': 'Kendaraan dengan plat',
      'telah_disetujui_admin': 'telah disetujui oleh admin.',
      'telah_ditolak_admin': 'telah ditolak oleh admin.',
      'no_plate': 'Tanpa Plat',
      'edit_pengumuman': 'Edit Pengumuman',
      'simpan': 'Simpan',
      'waktu_kegiatan_berlalu': 'Waktu kegiatan tidak boleh berlalu',
      'pengumuman_diperbarui': 'Pengumuman Diperbarui',
      'pilih_gambar': 'Pilih Gambar',
      'no_images_found': 'Tidak ada gambar ditemukan',
      'Notification': 'Notifikasi',
      'search_resident_placeholder': 'Cari nama penghuni',
      'no_name': 'Tanpa Nama',
      'no_address': 'Tanpa Alamat',
      'jumlah_kendaraan': 'Jumlah Kendaraan',
      'tamu': 'Tamu',
      'tanggal_kedatangan': 'Tanggal Kedatangan',
      'pilih_kategori': 'Pilih Kategori',
      'select_date': 'Pilih Tanggal',
      'wajib_diisi': 'Wajib diisi',
      'berhasil_kirim_permintaan': 'Berhasil mengirim permintaan',
      'terjadi_kesalahan': 'Terjadi kesalahan',
      'user_not_logged_in': 'User belum login',
      'pilih_jenis_kendaraan': 'Pilih Jenis Kendaraan',
      'hint_username': 'Masukkan username',
      'hint_password': 'Masukkan password',
      'konfirmasi_password': 'Konfirmasi Password',
      'hint_konfirmasi_password': 'Masukkan ulang password',
      'password_tidak_sama': 'Password tidak sama',
      'hint_alamat': 'Masukkan alamat lengkap',
      'hint_nomor_handphone': 'Masukkan nomor handphone',
      'loading': 'Memuat...',
      'ringkasan': 'Statistik',
      'total_user': 'Jumlah Penghuni',
    },
    'en': {
      'tentang_saya': 'About Me',
      'penghuni': 'Resident',
      'kendaraanku': 'My Vehicles',
      'unverified': 'Unverified',
      'verified': 'Verified',
      'kontak': 'Contact',
      'akun': 'Account',
      'data_pribadi': 'Personal Data',
      'pengaturan': 'Settings',
      'visi_misi': 'Vision & Mission',
      'ketentuan_privasi': 'Terms & Privacy',
      'keluar': 'Logout',
      'pilih_bahasa': 'Select Language',
      'bahasa': 'Language',
      'batal': 'Cancel',
      'halo': 'Hello',
      'selamat_datang': 'Welcome to Entrify',
      'menu_utama': 'Main Menu',
      'daftar_kendaraan': 'Vehicle List',
      'riwayat_kendaraan': 'Vehicle History',
      'pengumuman': 'Announcements',
      'see_more': 'See All',
      'info_pengumuman': 'Announcement Info this month',
      'tidak_ada_pengumuman': 'No announcements',
      'data_keluar_masuk': 'In/Out Data',
      'search_placeholder': 'Search plate/vehicle',
      'tidak_ada_data': 'No data found',
      'tanggal': 'Date',
      'status': 'Status',
      'jenis': 'Type',
      'masuk': 'In',
      'keluar_status': 'Out',
      'motor': 'Motorcycle',
      'mobil': 'Car',
      'semua': 'All',
      'hapus_filter': 'Clear Filter',
      'pilih': 'Select',
      'lihat_detail': 'View Details',
      'tambah_kendaraan': 'Add Vehicle',
      'pending': 'Pending',
      'rejected': 'Rejected',
      'periode': 'Period',
      'daftar_pengumuman': 'Announcement List',
      'informasi_pengumuman': 'Announcement Information',
      'visi_misi_content':
          'Vision:\nTo be the leading residential management platform that facilitates interaction between management and residents.\n\nMission:\n1. Provide transparent and efficient services.\n2. Improve environmental security and comfort.\n3. Build a harmonious community.',
      'kedatangan': 'Arrival',
      'foto_kendaraan': 'Vehicle Photo',
      'ketentuan_privasi_content':
          '1. User Data:\nWe maintain the confidentiality of your personal data and will not share it with third parties without permission.\n\n2. App Usage:\nThis application is used for residential management and communication between residents.\n\n3. Security:\nWe are committed to maintaining the security of data and transactions in this application.',
      'tutup': 'Close',
      'detail_kendaraan': 'Vehicle Detail',
      'nama_pemilik': 'Owner Name',
      'plat_kendaraan': 'Vehicle Plate',
      'jenis_kendaraan': 'Vehicle Type',
      'tanggal_waktu': 'Date & Time',
      'detail_pengumuman_title': 'Announcement Detail',
      'uploaded': 'Uploaded',
      'deskripsi': 'Description',
      'tanggal_kegiatan': 'Event Date',
      'uploaded_by': 'By',
      'pengurus_keamanan': 'Security Admin',
      'memuat': 'Loading...',
      'tambah_pengumuman': 'Add Announcement',
      'hapus_pengumuman': 'Delete Announcement',
      'konfirmasi_hapus_pengumuman':
          'Are you sure you want to delete this announcement?',
      'hapus': 'Delete',
      'pengumuman_dihapus': 'Announcement deleted successfully',
      'admin': 'Admin',
      'judul_kegiatan': 'Event Title',
      'hint_judul': 'Example: Community Cleanup',
      'hint_deskripsi': 'Describe the event...',
      'pilih_tanggal': 'Select Date',
      'jam_kegiatan': 'Event Time',
      'pilih_jam': 'Select Time',
      'submit': 'Submit',
      'pilih_tanggal_valid': 'Please select a date',
      'pilih_jam_valid': 'Please select a time',
      'pengumuman_ditambahkan': 'Announcement added successfully',
      'approved': 'Approved',
      'unknown': 'Unknown',
      'na': 'N/A',
      'approved_at': 'Approved at',
      'submitted_at': 'Submitted at',
      'rejected_at': 'Rejected at',
      'kategori': 'Category',
      'keterangan': 'Information',
      'foto': 'Photo',
      'tanggal_terdaftar': 'Registered Date',
      'approve': 'Approve',
      'reject': 'Reject',
      'confirm_approve': 'Are you sure you want to approve this vehicle?',
      'confirm_reject': 'Are you sure you want to reject this vehicle?',
      'vehicle_approved': 'Vehicle approved successfully',
      'vehicle_rejected': 'Vehicle rejected successfully',
      'daftar_penghuni': 'Resident List',
      'no_residents_found': 'No residents found',
      'tambah_penghuni': 'Add Resident',
      'nama_penghuni': 'Resident Name',
      'alamat_penghuni': 'Resident Address',
      'id_penghuni': 'Resident ID',
      'nomor_handphone': 'Phone Number',
      'penghuni_berhasil_ditambahkan': 'Resident added successfully',
      'id_sudah_digunakan': 'Resident ID already used',
      'username_sudah_digunakan': 'Username already used',
      'field_tidak_boleh_kosong': 'This field cannot be empty',
      'tidak_ada_kendaraan_terdaftar': 'No registered vehicles.',
      'error_loading_vehicles': 'Error loading vehicles',
      'username': 'Username',
      'password': 'Password',
      'alamat': 'Address',
      'kelola_penghuni': 'Manage\nResidents',
      'kelola_kendaraan': 'Manage\nVehicles',
      'error_loading_announcements': 'Error loading announcements',
      'kalender': 'Calendar',
      'no_title': 'No Title',
      'informasi_terbaru': 'Latest Information',
      'kegiatan_pada': 'Events on',
      'no_description': 'No description',
      'terdaftar': 'Registered',
      'Su': 'Sun',
      'Mo': 'Mon',
      'Tu': 'Tue',
      'We': 'Wed',
      'Th': 'Thu',
      'Fr': 'Fri',
      'Sa': 'Sat',
      'month_1': 'Jan',
      'month_2': 'Feb',
      'month_3': 'Mar',
      'month_4': 'Apr',
      'month_5': 'May',
      'month_6': 'Jun',
      'month_7': 'Jul',
      'month_8': 'Aug',
      'month_9': 'Sep',
      'month_10': 'Oct',
      'month_11': 'Nov',
      'month_12': 'Dec',
      'profil_admin': 'Admin Profile',
      'kantor_pengelola': 'Management Office',
      'kendaraan_disetujui': 'Vehicle Approved',
      'kendaraan_ditolak': 'Vehicle Rejected',
      'kendaraan_dengan_plat': 'Vehicle with plate',
      'telah_disetujui_admin': 'has been approved by admin.',
      'telah_ditolak_admin': 'has been rejected by admin.',
      'no_plate': 'No Plate',
      'edit_pengumuman': 'Edit Announcement',
      'simpan': 'Save',
      'waktu_kegiatan_berlalu': 'Event time cannot be in the past',
      'pengumuman_diperbarui': 'Announcement Updated',
      'pilih_gambar': 'Select Image',
      'no_images_found': 'No images found',
      'Notification': 'Notification',
      'search_resident_placeholder': 'Search resident name',
      'no_name': 'No Name',
      'no_address': 'No Address',
      'jumlah_kendaraan': 'Total Vehicles',
      'tamu': 'Guest',
      'tanggal_kedatangan': 'Arrival Date',
      'pilih_kategori': 'Select Category',
      'select_date': 'Select Date',
      'wajib_diisi': 'Required',
      'berhasil_kirim_permintaan': 'Request sent successfully',
      'terjadi_kesalahan': 'An error occurred',
      'user_not_logged_in': 'User not logged in',
      'pilih_jenis_kendaraan': 'Select Vehicle Type',
      'hint_username': 'Enter username',
      'hint_password': 'Enter password',
      'konfirmasi_password': 'Confirm Password',
      'hint_konfirmasi_password': 'Re-enter password',
      'password_tidak_sama': 'Passwords do not match',
      'hint_alamat': 'Enter full address',
      'hint_nomor_handphone': 'Enter phone number',
      'loading': 'Loading...',
      'ringkasan': 'Statistics',
      'total_user': 'Total Users',
    },
    'zh': {
      'tentang_saya': '关于我',
      'penghuni': '居民',
      'kendaraanku': '我的车辆',
      'unverified': '未验证',
      'verified': '已验证',
      'kontak': '联系方式',
      'akun': '账户',
      'data_pribadi': '个人资料',
      'pengaturan': '设置',
      'visi_misi': '愿景与使命',
      'ketentuan_privasi': '条款与隐私',
      'keluar': '退出',
      'pilih_bahasa': '选择语言',
      'bahasa': '语言',
      'batal': '取消',
      'halo': '你好',
      'selamat_datang': '欢迎来到 Entrify',
      'menu_utama': '主菜单',
      'daftar_kendaraan': '车辆\n列表',
      'riwayat_kendaraan': '车辆\n历史',
      'pengumuman': '公告',
      'see_more': '查看更多',
      'info_pengumuman': '本月公告信息',
      'tidak_ada_pengumuman': '暂无公告',
      'data_keluar_masuk': '车辆出入数据',
      'search_placeholder': '搜索车牌/类型',
      'tidak_ada_data': '未找到数据',
      'tanggal': '日期',
      'status': '状态',
      'jenis': '类型',
      'masuk': '入',
      'keluar_status': '出',
      'motor': '摩托车',
      'mobil': '汽车',
      'semua': '全部',
      'hapus_filter': '清除筛选',
      'pilih': '选择',
      'lihat_detail': '查看详情',
      'tambah_kendaraan': '添加车辆',
      'pending': '待处理',
      'rejected': '已拒绝',
      'periode': '期间',
      'daftar_pengumuman': '公告列表',
      'informasi_pengumuman': '公告详情',
      'visi_misi_content':
          '愿景：\n成为促进管理者与居民互动的领先住宅管理平台。\n\n使命：\n1. 提供透明高效的服务。\n2. 提高环境安全和舒适度。\n3. 建立和谐社区。',
      'ketentuan_privasi_content':
          '1. 用户数据：\n我们要保护您的个人数据机密性，未经许可不会与第三方共享。\n\n2. 应用使用：\n此应用程序用于住宅管理和居民之间的沟通。\n\n3. 安全：\n我们致力于维护此应用程序中数据和交易的安全。',
      'tutup': '关闭',
      'detail_kendaraan': '车辆详情',
      'nama_pemilik': '车主姓名',
      'plat_kendaraan': '车牌号',
      'jenis_kendaraan': '车辆类型',
      'tanggal_waktu': '日期和时间',
      'detail_pengumuman_title': '公告详情',
      'uploaded': '上传于',
      'deskripsi': '描述',
      'tanggal_kegiatan': '活动日期',
      'uploaded_by': '由',
      'pengurus_keamanan': '安全管理员',
      'memuat': '加载中...',
      'tambah_pengumuman': '添加公告',
      'hapus_pengumuman': '删除公告',
      'konfirmasi_hapus_pengumuman': '您确定要删除此公告吗？',
      'hapus': '删除',
      'pengumuman_dihapus': '公告删除成功',
      'admin': '管理员',
      'judul_kegiatan': '活动标题',
      'hint_judul': '例如：社区清洁',
      'hint_deskripsi': '描述活动...',
      'pilih_tanggal': '选择日期',
      'jam_kegiatan': '活动时间',
      'pilih_jam': '选择时间',
      'submit': '提交',
      'pilih_tanggal_valid': '请选择日期',
      'pilih_jam_valid': '请选择时间',
      'pengumuman_ditambahkan': '公告添加成功',
      'approved': '已批准',
      'unknown': '未知',
      'na': 'N/A',
      'approved_at': '批准于',
      'submitted_at': '提交于',
      'rejected_at': '拒绝于',
      'kategori': '类别',
      'keterangan': '信息',
      'foto': '照片',
      'tanggal_terdaftar': '注册日期',
      'approve': '批准',
      'reject': '拒绝',
      'confirm_approve': '您确定要批准这辆车吗？',
      'confirm_reject': '您确定要拒绝这辆车吗？',
      'vehicle_approved': '车辆已批准',
      'vehicle_rejected': '车辆已拒绝',
      'daftar_penghuni': '居民列表',
      'no_residents_found': '未找到居民',
      'tambah_penghuni': '添加居民',
      'nama_penghuni': '居民姓名',
      'alamat_penghuni': '居民地址',
      'id_penghuni': '居民ID',
      'nomor_handphone': '手机号码',
      'penghuni_berhasil_ditambahkan': '居民添加成功',
      'id_sudah_digunakan': '居民ID已被使用',
      'username_sudah_digunakan': '用户名已被使用',
      'field_tidak_boleh_kosong': '此字段不能为空',
      'tidak_ada_kendaraan_terdaftar': '没有注册车辆。',
      'error_loading_vehicles': '加载车辆时出错',
      'username': '用户名',
      'password': '密码',
      'alamat': '地址',
      'kelola_penghuni': '管理\n居民',
      'kelola_kendaraan': '管理\n车辆',
      'error_loading_announcements': '加载公告时出错',
      'kalender': '日历',
      'no_title': '无标题',
      'informasi_terbaru': '最新信息',
      'kegiatan_pada': '活动于',
      'no_description': '无描述',
      'terdaftar': '已注册',
      'Su': '周日',
      'Mo': '周一',
      'Tu': '周二',
      'We': '周三',
      'Th': '周四',
      'Fr': '周五',
      'Sa': '周六',
      'month_1': '1月',
      'month_2': '2月',
      'month_3': '3月',
      'month_4': '4月',
      'month_5': '5月',
      'month_6': '6月',
      'month_7': '7月',
      'month_8': '8月',
      'month_9': '9月',
      'month_10': '10月',
      'month_11': '11月',
      'month_12': '12月',
      'profil_admin': '管理员资料',
      'kantor_pengelola': '管理处',
      'kendaraan_disetujui': '车辆已批准',
      'kendaraan_ditolak': '车辆已拒绝',
      'kendaraan_dengan_plat': '车牌号为',
      'telah_disetujui_admin': '的车辆已被管理员批准。',
      'telah_ditolak_admin': '的车辆已被管理员拒绝。',
      'no_plate': '无车牌',
      'edit_pengumuman': '编辑公告',
      'simpan': '保存',
      'waktu_kegiatan_berlalu': '活动时间不能是过去的时间',
      'pengumuman_diperbarui': '公告已更新',
      'pilih_gambar': '选择图片',
      'no_images_found': '未找到图片',
      'Notification': '通知',
      'search_resident_placeholder': '搜索居民姓名',
      'no_name': '无名',
      'no_address': '无地址',
      'jumlah_kendaraan': '车辆总数',
      'tamu': '访客',
      'tanggal_kedatangan': '到达日期',
      'pilih_kategori': '选择类别',
      'select_date': '选择日期',
      'wajib_diisi': '必填',
      'berhasil_kirim_permintaan': '请求发送成功',
      'terjadi_kesalahan': '发生错误',
      'user_not_logged_in': '用户未登录',
      'pilih_jenis_kendaraan': '选择车辆类型',
      'hint_username': '输入用户名',
      'hint_password': '输入密码',
      'konfirmasi_password': '确认密码',
      'hint_konfirmasi_password': '重新输入密码',
      'password_tidak_sama': '密码不匹配',
      'hint_alamat': '输入完整地址',
      'hint_nomor_handphone': '输入手机号码',
      'loading': '加载中...',
      'ringkasan': '统计',
      'total_user': '居民总数',
    },
  };
}

// Helper function for easier access
String tr(String key) => LocalizationService().translate(key);
