// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbzaHcfTieeAPiP56VMxku2zShz1RJEWM',
    appId: '1:26816535488:web:cfb848cc215fde5b85c625',
    messagingSenderId: '26816535488',
    projectId: 'smartgate-a021d',
    authDomain: 'smartgate-a021d.firebaseapp.com',
    storageBucket: 'smartgate-a021d.firebasestorage.app',
    measurementId: 'G-E5JGXPVZ33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtCaLWlGbAv-Voh3neY2Dy8uDtQT2nFwg',
    appId: '1:26816535488:android:ff61a182c93832ed85c625',
    messagingSenderId: '26816535488',
    projectId: 'smartgate-a021d',
    storageBucket: 'smartgate-a021d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvIKqJGRgIL6PiM-w60IpjCXVIfQzvNX4',
    appId: '1:26816535488:ios:f85e9a347b531f6285c625',
    messagingSenderId: '26816535488',
    projectId: 'smartgate-a021d',
    storageBucket: 'smartgate-a021d.firebasestorage.app',
    iosBundleId: 'com.example.expo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvIKqJGRgIL6PiM-w60IpjCXVIfQzvNX4',
    appId: '1:26816535488:ios:f85e9a347b531f6285c625',
    messagingSenderId: '26816535488',
    projectId: 'smartgate-a021d',
    storageBucket: 'smartgate-a021d.firebasestorage.app',
    iosBundleId: 'com.example.expo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbzaHcfTieeAPiP56VMxku2zShz1RJEWM',
    appId: '1:26816535488:web:83b71fc31b0b59cd85c625',
    messagingSenderId: '26816535488',
    projectId: 'smartgate-a021d',
    authDomain: 'smartgate-a021d.firebaseapp.com',
    storageBucket: 'smartgate-a021d.firebasestorage.app',
    measurementId: 'G-QLCNTR3BSX',
  );
}
